### ISSUE TITLE
WebSocket connection to 'wss://steemd.steemit.com/' failed

### ISSUE THREAD

**Issue by joticajulian** [steemit/steem-js#313]
I made a tool for steemit and It worked very well the last 6 months ([steem activity](https://joticajulian.github.io/steem-activity/index.html?account=jga)). However, this week it failed. This is the error

```WebSocket connection to 'wss://steemd.steemit.com/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT (steem.min.js:5)``` 
```Error: The WS connection was closed before this operation was made at WebSocket.<anonymous> (steem.min.js:5) undefined```

#### How to reproduce
I get the error when I run every function, for instance:

```
steem.api.getDynamicGlobalProperties(function(err, result){
    console.log(err, result);
});
```

When I call the library I use:
```<script src="https://cdn.steemjs.com/lib/latest/steem.min.js"></script>```

**Comment by bycz6** [comment]
Check that

https://steemit.com/steemitdev/@steemitdev/last-chance-to-update-steemd-steemit-com-will-be-retired-on-january-6

Em 08/01/2018 2:51 p.m., "joticajulian" <notifications@github.com> escreveu:

I made a tool for steemit and It worked very well the last 6 months (steem
activity
<https://joticajulian.github.io/steem-activity/index.html?account=jga>).
However, this week it failed. This is the error

WebSocket connection to 'wss://steemd.steemit.com/' failed: Error in
connection establishment: net::ERR_CONNECTION_TIMED_OUT (steem.min.js:5)
Error: The WS connection was closed before this operation was made at
WebSocket.<anonymous> (steem.min.js:5) undefined
How to reproduce

I get the error when I run every function, for instance:

steem.api.getDynamicGlobalProperties(function(err, result){
    console.log(err, result);
});

When I call the library I use:
<script src="https://cdn.steemjs.com/lib/latest/steem.min.js"></script>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/steemit/steem-js/issues/313>, or mute the thread

**Comment by bobinson** [comment]
#312 related to this

**Comment by thrize** [comment]
For the moment you can use this code to use @Gandalf-the-Grey 's server instead

```steem.config.set('websocket','wss://gtg.steem.house:8090');```

**Comment by DestBest** [comment]
`steem.config.set('websocket','wss://gtg.steem.house:8090');`

Worked for me, thanks !

**Comment by thrize** [comment]
FYI this also works and is preferred, chalk it up to tiredness that I didn't cop this before:

```steem.api.setOptions({ url: 'https://api.steemit.com'});```

**Comment by joticajulian** [comment]
```steem.api.setOptions({ url: 'https://api.steemit.com'});```

Worked for me, thanks!

**Comment by bonustrack** [comment]
If you having this issue you should update to the last version of `steem` which use the endpoint `https://api.steemit.com` by default or change the endpoint manually as suggested below.

**Comment by thrize** [comment]
0.7.1 is not marked as the latest release on GitHub. I missed that it was updated on NPM, that's great
